server:
  port: 8843
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://115.29.201.100:3306/db_user?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: qTfGhoa%.9UvxTru
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 20000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  main:
    banner-mode: off
mybatis:
  mapper-locations: classpath:/mybatis/mapping/*.xml
  type-aliases-package: com.chenum.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.chenum: debug
nacos:
  server-address: ${NACOS-ADDRESS:43.143.115.227}
  port: ${NACOS-PORT:8848}
  username: ${NACOS-USERNAME:nacos}
  password: ${NACOS-PASSWORD:6wRCCwK78WANNL}
  discovery:
    auto-register: true
    namespace: 7bc13313-7c4d-45a8-bf9f-415fa8678961
    register:
      enabled: true
      group-name: blog
      service-name: ${spring.application.name}
    server-addr: ${nacos.server-address}:${nacos.port}
    username: ${nacos.username}
    password: ${nacos.password}
  config:
    data-id: blog-data-id
    group: blog
    auto-refresh: true
    namespace: 7bc13313-7c4d-45a8-bf9f-415fa8678961
    server-addr: ${nacos.server-address}:${nacos.port}
    bootstrap:
      enable: true
    username: ${nacos.username}
    password: ${nacos.password}
management:
  endpoints:
    web:
      base-path: /health
dubbo:
  application:
    name: userservice-provider
    register-consumer: false
  protocol:
    name: dubbo
    port: 20880
    #    optimizer: org.apache.dubbo.common.serialize.fastjson2.FastJson2Serialization
    serialization: nativejava
  registry:
    id: nacos-registry
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
    group: blog
    parameters:
      namespace: 7bc13313-7c4d-45a8-bf9f-415fa8678961
  provider:
    group: blog

