server:
  port: 8842
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: blogservice
  datasource:
    url: jdbc:mysql://115.29.201.100:3306/db_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: qTfGhoa%.9UvxTru
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 20000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  main:
    banner-mode: off
mybatis:
  mapper-locations: classpath:/mybatis/mapping/*.xml
  type-aliases-package: com.chenum.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
com:
  chenum:
#    using in:email : https://api.github.com/search/users?q=bmartel+in%3Aemail
#    using in:username : https://api.github.com/search/users?q=Bertrand+Martel+in%3Ausername
    avatar-url: https://avatars.githubusercontent.com/{username}
