server:
  port: 8842
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: blog service
  datasource:
    url: jdbc:mysql://115.29.201.100:3306/db_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: linzifeng524.
mybatis:
  mapper-locations: classpath:/mybatis/mapping/*.xml
  type-aliases-package: com.chenum.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
