server:
  port: 8848
spring:
  application:
    name: blog service
  datasource:
    url: jdbc:mysql://115.29.201.100:3306/db_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: linzifeng524.